---
title: "Untitled"
author: "Jasen Zhang"
date: "5/8/2025"
output: pdf_document
---

```{r}
library(tidyverse)
source('Jasen_GraphPP_FUN.R')
```

```{r}
ffs = 1
set.seed(ffs)

nrep = 100
ncores = 2

## simulation setting

pseq = 40
nseq = c(400,500,600)

np_seq = cbind(rep(pseq, each=length(nseq)), 
               rep(nseq, length(pseq)))

simu_now  = "simu1"
rep_num = ffs %% nrep
if(rep_num==0){rep_num=100}

np_ind = ceiling(ffs/nrep)
p = np_seq[np_ind,1]
ntrain = np_seq[np_ind,2]

simu_file = paste(simu_now, ".R",sep="")

source(file = simu_file)
```

```{r}
patient_sel = 1:ntrain
feature_sel = 1:p
Tseq = seq(0.05,0.95,length=19)
dmax = 3
FVE_thre = 0.9

quantile(data_df[,(.N),by=c("subject_num","feature_id")]$V1)
```

# Step 1: choose a density function and construct kernel using (8)

### entire get_rho_diag_pp function

```{r}
data_all <- data_df
dmax <- 4
gamma_ratio <- 1
gamma_max <- 100
remove_diag <- T
ncores <- 3

p = length(feature_sel) ## number of processes

#### estimate intensity ###
NN = length(patient_sel)
data_all = data_all[is.element(feature_id, feature_sel),]
data_all = data_all[is.element(subject_num, patient_sel),]

res = mclapply(feature_sel, function(i){
  
  # for each mark, parallelize this computation
  
  # extract info for mark i
  data_i = data_all[feature_id==i,]
  data_i_count = data_i[,.(count=.N),by="subject_num"]

  
  # gamma = 1/h_i^2
  gamma = get_gamma(data_i$time)*gamma_ratio
  gamma[is.na(gamma)] = gamma_max # if the get_gamma() function returned NA, fill it in with gamma_max

  
  # get w_h(t) denominator term for each Tseq
  
  # missing multiplying by 1 / sqrt(2 * pi * h^2)
  denom = sapply(Tseq, function(x){
    truncNorm_denom(x,gamma,0,1)
  })
  
  # obtain intensities for all k replicates at all Tseq times
  intensity    = data_i[,get_intensity(time,Tseq,gamma,denom),by=c("subject_num")] # for each subject with non-zero amount of events of mark i, compute the intensity at all Tseq (19) points
  intensity_v2 = data_i[,get_intensity_v2(time,Tseq,gamma,denom),by=c("subject_num")]
  
  
  
  patient_now = unique(intensity$subject_num)                          # patient IDs for mark i that have at least one event (under 400)
  intensity = matrix(intensity$V1,nrow=length(Tseq))                   # rearrange to be a 19 x 380 matrix
  data_i_count = data_i_count[match(patient_now, subject_num),]        # count table for number of events 
  mu = apply(intensity, 1, sum) / NN                                   # rho_i(t) for mark i 
  

  # now, obtain bivariate intensity in equation (12)
  diag_mat = data_i[,get_diag_mat(time,Tseq,gamma,denom),by=c("subject_num")]   # for all k subjects, compute the 19 x 19 matrix entries
  diag_mat = matrix(diag_mat$V1,nrow=length(Tseq)*length(Tseq))                 # rearrange into a 361 x k matrix
  diag_mat = apply(diag_mat, 1, sum)                                            # take the sum across k subjects to return a 361-lengthed vector
  diag_mat = matrix(diag_mat, length(Tseq), length(Tseq))                       # rearrange it to be a 19 x 19 matrix
  # we now have a matrix that is 

  
  # return the following:
  # data_i_count = xi_i^k counts
  # intensity = 19 x n matrix of intensities for all replicates across 19 prespecified timepoints
  # mu = average intensity across all replicates for each of the 19 pre-specified timepoints
  # diag_mat = 19 x 19 matrix 
  # gamma = h_i bandwidth parameter
  list(data_i_count=data_i_count, intensity=intensity, 
       mu = mu, diag_mat=diag_mat, gamma=gamma)
}, mc.cores = ncores)

gamma_vec = sapply(res, function(x){
  x$gamma
})

rho_diag = mclapply(res, function(xx){
  
  Sigma_ii = cross_prod(X=xx,NN=NN,remove_diag=remove_diag)
  ## pca with svd
  eigen_res = eigen(Sigma_ii)
  eigen_res$values[ eigen_res$values<0] = 0 
  positiveInd = eigen_res$values >= 0
  d = eigen_res$values[positiveInd]
  eigenV = eigen_res$vectors[, positiveInd, drop=FALSE]
  FVE = cumsum(d) / sum(d)
  
  d = d[1:dmax]
  if(any(d < 0)){stop("negative d values!")}
  eigenV = eigenV[, 1:dmax, drop=FALSE]
  
  cov_diag = t(eigenV) %*% Sigma_ii %*% eigenV
  list(d = d, eigenV = eigenV, cumFVE = FVE, 
       cov = diag(diag(cov_diag),length(d),length(d)),Sigma_ii=Sigma_ii)
}, mc.cores = ncores)

list(res=res,rho_diag=rho_diag, gamma_vec=gamma_vec)
```



