---
title: "Untitled"
author: "Jasen Zhang"
date: "5/30/2025"
output: pdf_document
---

```{r}
source('unpack_functions.R')


load('/u/home/j/jasenzz/Graphical_Cox_Process/GMpp-main/spike_data/Brain_Region.RData')


n <- 50   
movements <- c(0, 1, 2) # movement is either both (0) resting (1) or moving (2)
VR <- 0
epoch_or_week <- 'week'
ew_nums <- c(18, 22, 26)
min_edges <- 1
first_root <- "/u/home/j/jasenzz/Graphical_Cox_Process/GMpp-main/results_alzheimers/week_move_1/"
# IDs <- c('346', '351', '366', '361', '362', '368')  # mouse ID
# ID2 <- c('Tau1', 'Tau2', 'Tau3', 'WT1', 'WT2', 'WT3') # our name 
# 
# IDs <- c('346', '351', '366', '361')  # mouse ID
# ID2 <- c('Tau1', 'Tau2', 'Tau3', 'WT1') # our name 

for(movement in movements){
  for(ew_num in ew_nums){
    unpack(n, movement, VR, epoch_or_week, ew_num, min_edges, df_brain_region, first_root)
    
    print('done')
  }
}

# moving over time
ID2 <- c('Tau1', 'WT1')
movements <- c(0, 1, 2)

for(movement in movements){
  for(mouse_ID in ID2){
    unpack_over_time(n, movement, VR, epoch_or_week, ew_nums, mouse_ID, min_edges, df_brain_region, first_root)
  }
}

```

## Task 2

- n = 50
- every week
- Movement = 0, 1, 2
- me = 1

```{r}
source('unpack_functions.R')


load('/u/home/j/jasenzz/Graphical_Cox_Process/GMpp-main/spike_data/Brain_Region.RData')


first_root <- "/u/home/j/jasenzz/Graphical_Cox_Process/GMpp-main/results_alzheimers/task_02"
folder_names <- list.files(path = first_root, full.names = TRUE)
folder_params <- extract_pieces(folder_names)

summary_df <- data.frame()
first <- T

for(i in 1:length(folder_names)){ # for each folder
  
  folder_i <- folder_names[i]
  
  epoch_or_week <- folder_params$epoch_or_week[i]
  n <- folder_params$replicate[i]
  movement <- folder_params$movement[i]
  VR <- folder_params$VR[i]
  ew_num <- folder_params$ew_num[i]
  min_edges <- folder_params$min_edge[i]
  
  file_names <- list.files(path = folder_i, full.names = TRUE) # get the .rda file names within each folder
  
  mouse_IDs <- extract_pieces2(file_names) # get the mouse names
  
  for(j in 1:length(file_names)){ # for each mouse
    result_ij <- unpack_tabular_summary(n, movement, VR, epoch_or_week, ew_num, mouse_IDs[j], min_edges, df_brain_region, file_names[j])
    
    summary_df <- rbind(summary_df, result_ij)
  }
   
  
}

# fix data types for each column

summary_df[-which(names(summary_df) == "mouse_ID")] <- lapply(summary_df[-which(names(summary_df) == "mouse_ID")], as.numeric)
summary_df$mouse_ID <- factor(summary_df$mouse_ID)

# change movement from 0, 1, 2 to 'both', 'resting', 'running' respectively

movement_factor <- rep('Running', nrow(summary_df))
movement_factor[summary_df$movement == 0] <- 'Both'
movement_factor[summary_df$movement == 1] <- 'Resting'
movement_factor <- factor(movement_factor, levels = c('Both', 'Resting', 'Running'))
summary_df$movement_factor <- movement_factor

# same for VR: 0, 1, 2 are 'both', 'off', 'on' respectively

VR_factor <- rep('On', nrow(summary_df))
VR_factor[summary_df$VR == 0] <- 'Both'
VR_factor[summary_df$VR == 1] <- 'Off'
VR_factor <- factor(VR_factor, levels = c('Both', 'Off', 'On'))
summary_df$VR_factor <- VR_factor

## graphing the summary statistics over time

mice_strains2 <- c(
  "Tau1" = "lightcoral",
  "Tau2" = "red",
  "Tau3" = "darkred",
  "WT1" = "lightgreen",
  "WT2" = "green",
  "WT3" = "darkgreen"
)

graphs <- list()

# average degree over time

graphs[['avg_deg']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = avg_deg, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = avg_deg, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Average Degree') + 
  xlab('Age (Weeks)') + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# proportion of non-singletons

summary_df$pct_non_singletons <- 100 * summary_df$num_con_verts/summary_df$num_candidates

graphs[['pct_non_singletons']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_non_singletons, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_non_singletons, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of non-Singletons') + 
  xlab('Age (Weeks)') + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# proportion of inter-region connections

summary_df$pct_inter_region_edge <- 100 * summary_df$num_HE_edges/summary_df$num_edges
summary_df$pct_HH_edge <- 100 * summary_df$num_HH_edges/summary_df$num_edges
summary_df$pct_EE_edge <- 100 * summary_df$num_EE_edges/summary_df$num_edges

graphs[['pct_HE']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_inter_region_edge, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_inter_region_edge, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of Inter-Region Edges') + 
  xlab('Age (Weeks)') + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# pct HH edges

graphs[['pct_HH']]  <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_HH_edge, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_HH_edge, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of HIP-HIP Edges') + 
  xlab('Age (Weeks)') + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# pct EE edges

graphs[['pct_EE']]  <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_EE_edge, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_EE_edge, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of EHC-EHC Edges') + 
  xlab('Age (Weeks)') + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# 4) proportion of candidate neurons out of total neurons

summary_df$pct_candidate_neurons <- 100 * summary_df$num_candidates/summary_df$num_neurons

graphs[['pct_candidates']]  <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_candidate_neurons, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_candidate_neurons, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of non-discarded Neurons') + 
  xlab('Age (Weeks)') + 
  ylim(c(0, 100)) + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# save data

final_results_dir <- "/u/home/j/jasenzz/Graphical_Cox_Process/GMpp-main/results_alzheimers/task_02_figs/"
  
if (!dir.exists(final_results_dir)) {
  dir.create(final_results_dir)
}

# store summary statistics of each fit

write.csv(summary_df, file = paste0(final_results_dir, 'graph_statistics.csv'), row.names = FALSE)

# graphs

pdf(paste0(final_results_dir, 'graph_statistics.pdf'), width = 8, height = 3)
g1
g2
g3
g3a
g3b
g4
dev.off()
```


## Task 4

- time_scale = 10
- by epoch
- Movement = 0, 1, 2
- VR = 0
- me = 1

```{r}
source('unpack_functions.R')


load('/u/home/j/jasenzz/Graphical_Cox_Process/GMpp-main/spike_data/Brain_Region.RData')


first_root <- "/u/home/j/jasenzz/Graphical_Cox_Process/GMpp-main/results_alzheimers/task_04"
folder_names <- list.files(path = first_root, full.names = TRUE)
folder_params <- extract_pieces(folder_names)

summary_df <- data.frame()
first <- T

for(i in 1:length(folder_names)){ # for each folder
  
  folder_i <- folder_names[i]
  
  epoch_or_week <- folder_params$epoch_or_week[i]
  rep_or_ts <- folder_params$rep_or_ts[i] 
  rep_ts_num <- folder_params$rep_ts_num[i]
  movement <- folder_params$movement[i]
  VR <- folder_params$VR[i]
  ew_num <- folder_params$ew_num[i]
  min_edges <- folder_params$min_edge[i]
  
  file_names <- list.files(path = folder_i, full.names = TRUE) # get the .rda file names within each folder
  
  mouse_IDs <- extract_pieces2(file_names) # get the mouse names
  
  for(j in 1:length(file_names)){ # for each mouse
    result_ij <- unpack_tabular_summary(n, movement, VR, epoch_or_week, ew_num, rep_or_ts, rep_ts_num, mouse_IDs[j], min_edges, df_brain_region, file_names[j])
    
    summary_df <- rbind(summary_df, result_ij)
  }
   
  
}

# fix data types for each column

summary_df[-which(names(summary_df) == "mouse_ID")] <- lapply(summary_df[-which(names(summary_df) == "mouse_ID")], as.numeric)
summary_df$mouse_ID <- factor(summary_df$mouse_ID)

# change movement from 0, 1, 2 to 'both', 'resting', 'running' respectively

movement_factor <- rep('Running', nrow(summary_df))
movement_factor[summary_df$movement == 0] <- 'Both'
movement_factor[summary_df$movement == 1] <- 'Resting'
movement_factor <- factor(movement_factor, levels = c('Both', 'Resting', 'Running'))
summary_df$movement_factor <- movement_factor

# same for VR: 0, 1, 2 are 'both', 'off', 'on' respectively

VR_factor <- rep('On', nrow(summary_df))
VR_factor[summary_df$VR == 0] <- 'Both'
VR_factor[summary_df$VR == 1] <- 'Off'
VR_factor <- factor(VR_factor, levels = c('Both', 'Off', 'On'))
summary_df$VR_factor <- VR_factor

## graphing the summary statistics over time

mice_strains2 <- c(
  "Tau1" = "lightcoral",
  "Tau2" = "red",
  "Tau3" = "darkred",
  "WT1" = "lightgreen",
  "WT2" = "green",
  "WT3" = "darkgreen"
)

x_graph_title <- ('Epoch')
graphs <- list()

# average degree over time

graphs[['avg_deg']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = avg_deg, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = avg_deg, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Average Degree') + 
  xlab(x_graph_title) + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# proportion of non-singletons

summary_df$pct_non_singletons <- 100 * summary_df$num_con_verts/summary_df$num_candidates

graphs[['pct_non_singleton']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_non_singletons, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_non_singletons, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of non-Singletons') + 
  ylim(c(0, 100)) + 
  xlab(x_graph_title) + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# proportion of inter-region connections

summary_df$pct_inter_region_edge <- 100 * summary_df$num_HE_edges/summary_df$num_edges
summary_df$pct_HH_edge <- 100 * summary_df$num_HH_edges/summary_df$num_edges
summary_df$pct_EE_edge <- 100 * summary_df$num_EE_edges/summary_df$num_edges

graphs[['pct_HE']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_inter_region_edge, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_inter_region_edge, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of Inter-Region Edges') + 
  ylim(c(0, 100)) + 
  xlab(x_graph_title) + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# pct HH edges

graphs[['pct_HH']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_HH_edge, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_HH_edge, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of HIP-HIP Edges') + 
  ylim(c(0, 100)) + 
  xlab(x_graph_title) + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# pct EE edges

graphs[['pct_EE']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_EE_edge, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_EE_edge, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of EHC-EHC Edges') + 
  ylim(c(0, 100)) + 
  xlab(x_graph_title) + 
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# 4) proportion of candidate neurons out of total neurons

summary_df$pct_candidate_neurons <- 100 * summary_df$num_candidates/summary_df$num_neurons

graphs[['pct_candidates']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = pct_candidate_neurons, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = pct_candidate_neurons, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Percentage of non-discarded Neurons') + 
  ylim(c(0, 100)) + 
  xlab(x_graph_title) +  
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# 5) number of components

graphs[['num_components']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = num_comps, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = num_comps, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Number of Components') + 
  xlab(x_graph_title) +  
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# 6) number of replicates
graphs[['num_replicates']] <- ggplot() + 
  geom_point(data = summary_df, aes(x = ew_num, y = num_replicates, color = mouse_ID)) + 
  geom_line(data = summary_df, aes(x = ew_num, y = num_replicates, color = mouse_ID)) + 
  facet_wrap(~ movement_factor) + 
  ylab('Number of Replicates') + 
  xlab(x_graph_title) +  
  theme_bw() + 
  scale_color_manual(values = mice_strains2)

# save data

final_results_dir <- "/u/home/j/jasenzz/Graphical_Cox_Process/GMpp-main/results_alzheimers/task_04_figs/"
  
if (!dir.exists(final_results_dir)) {
  dir.create(final_results_dir)
}

# store summary statistics of each fit

write.csv(summary_df, file = paste0(final_results_dir, 'graph_statistics.csv'), row.names = FALSE)

# graphs

pdf(paste0(final_results_dir, 'graph_statistics.pdf'), width = 8, height = 3)
for(name_i in names(graphs)){
  print(graphs[[name_i]])
}
dev.off()
```




