source('functions/00a_matrix_massaging.R')
source('functions/00b_matrix_norms.R')
source('functions/00c_block_matrix_arrange.R')
source('functions/01_kernel_estimation.R')
source('functions/01a_kernel_initialization.R')
source('functions/01b_greshgorin_kernel_initialization.R')
source('functions/02_intensity_estimation.R')
source('functions/03_covariance_function_estimation.R')
source('functions/03a_subject_covariance_function.R')
source('functions/04_eigendecomposition.R')
source('functions/05_KL_coefficients.R')
source('functions/05a_KL_cross_coeffs.R')
source('functions/06_kernel_matrix.R')
source('functions/07_regression_operator.R')
# source('functions/07a_regression_operator_speedups.R')
source('functions/08_conditional_covariance.R')
source('functions/09_conditional_correlation.R')
source('functions/10_precision_operator.R')
source('functions/11_graph_estimation.R')
source('functions/12_full_estimation_procedure.R')
source('functions/13_estimation_validation.R')

library(dplyr)
library(data.table)